version: "3.7"
services:
  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - database

  database:
    build:
      context: ./database
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: # input password here
      MYSQL_DATABASE: pinjam_lab
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
